### ISSUE TITLE
Benchmark async vs sync base directory detection

### ISSUE THREAD

**Issue by marionebl** [xojs/atom-linter-xo#52]
https://github.com/sindresorhus/atom-linter-xo/pull/47 introduces async detection of the current base directory for `xo` to resolve from and run in. This caused some [discussion](https://github.com/sindresorhus/atom-linter-xo/pull/47#discussion_r89042457) about the performance implications.

To resolve this properly we should gain some data on

* overall hit of the detection on the performance budget
* performance comparison for both approaches
* performance in certain conditions (e.g. shallow vs. deep  file trees)

**Comment by sindresorhus** [comment]
Async is probably better regardless, so closing this.
