### ISSUE TITLE
Different results from atom linter to cli

### ISSUE THREAD

**Issue by OmgImAlexis** [xojs/atom-linter-xo#72]
If I run xo in terminal I don't get any issues for my file yet in atom I get warnings about `Casting of jquery does not match the underlying filesystem. (import/no-unresolved)` even thought jquery is added to my `package.json`.

Here's the first line in my file. I can provide more details if I know what's needed.

```
import {jQuery as $} from 'jquery';
```

I've also tried `import $ from 'jquery';` and still have the same issue.

**Comment by OmgImAlexis** [comment]
This may be related to https://github.com/benmosher/eslint-plugin-import/issues/720 but I'm not sure on that as I'm using OSX with a path of `/Users/xo/code/medusa/static/js/helpers/config.js`

**Comment by sindresorhus** [comment]
Is this still valid?

**Comment by OmgImAlexis** [comment]
Honestly not sure. 🤷‍♀
