### ISSUE TITLE
Linter v2 update not showing error id in description

### ISSUE THREAD

**Issue by OmgImAlexis** [xojs/atom-linter-xo#76]
As you can see the actual package/error it's violating is missing meaning I can't just add `// eslint-ignore` since I'm not sure which rule the problem is for.

![screen shot 2017-05-02 at 4 31 17 pm](https://cloud.githubusercontent.com/assets/6525926/25607241/d9ee94b8-2f54-11e7-883f-f3b537f64cd7.png)

**Comment by sindresorhus** [comment]
Is this still an issue? I think this was a problem with Linter and not this plugin specifically.

**Comment by OmgImAlexis** [comment]
Yep, looks like it's fixed.
