### ISSUE TITLE
Get true file case on Windows/OSX?

### ISSUE THREAD

**Issue by Arcanemagus** [xojs/atom-linter-xo#78]
There was recently [an issue](https://github.com/benmosher/eslint-plugin-import/issues/831) filed by @OmgImAlexis in `eslint-plugin-import` about how their opening of a file using the wrong case caused a lint message, even though the real filesystem file was correct.

I'm thinking about bringing in [true-case-path](https://www.npmjs.com/package/true-case-path) in `linter-eslint` to work around this limitation in Atom until it can be fixed there, and figured I'd file an issue here to see what you thought about for a solution to this (since @OmgImAlexis is actually using this package).

**Comment by sindresorhus** [comment]
Can you open a new issue on Atom? The referenced Atom issue is about Windows only.

**Comment by Arcanemagus** [comment]
I'd rather see this fixed in Atom as well, but it likely won't be brought in till Atom v1.18.0 at the absolute earliest so a workaround in the packages is the only solution till that comes through.

Made a note on that issue that this isn't Windows only as that's a very good point.

**Comment by sindresorhus** [comment]
@Arcanemagus Maintainers usually don't respond to comments on old issues. I'm talking from experience as a maintainer. I would recommend opening a new issue, and mention it being a problem on both macOS and Windows.

**Comment by Arcanemagus** [comment]
Filed https://github.com/atom/atom/issues/14402 with steps to reproduce included.

**Comment by sindresorhus** [comment]
Atom auto-closed https://github.com/atom/atom/issues/14402 They don't care and I don't care. Find a better editor I guess.
