### ISSUE TITLE
atom-linter-xo issues with atom 1.17.0

### ISSUE THREAD

**Issue by teehemkay** [xojs/atom-linter-xo#79]
After upgrading to Atom 1.17.0,  I'm getting the following error message dozens of times many files that previously didn't have any issue.

`Resolve error: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".`

This is with version 0.23.0 of atom-linter-xo and linter 2.1.4

Anyone else seeing this problem?

**Comment by sindresorhus** [comment]
Seems like this was fixed as no one else has reported this and I cannot reproduce.
