### ISSUE TITLE
some rules in unicorn not found

### ISSUE THREAD

**Issue by leftjs** [xojs/atom-linter-xo#80]
I'm using node v8, so this is the reason of this error?
![image](https://cloud.githubusercontent.com/assets/8311633/26643888/6f149db8-4665-11e7-878a-80a640508537.png)

**Comment by angussidney** [comment]
I'm getting this error too. Maybe due to the recent(ish) Atom update?

**Comment by dreamy-sk** [comment]
Same here. :( No clue what causes this.

**Comment by dreamy-sk** [comment]
#74 is probably the same issue, it has something to do with the new boosted start, it doesn't load dependencies correctly.

**Comment by lsunsi** [comment]
How are we on this issue? It really hurts usability on current atom version, so I'd say this is a major problem.

**Comment by davidbayo10** [comment]
```
atom --version
Atom    : 1.17.2
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

node --version
v6.11.0
```

Same problem!

**Comment by apertureless** [comment]
Same problem here. :C

```
❯ atom --version
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by Rowno** [comment]
Try upgrading XO, if you're using Yarn or npm 5 you'll need to remove/add `xo` so that it's dependencies get updated in the lockfile. See https://github.com/sindresorhus/atom-linter-xo/issues/74

**Comment by jaschaephraim** [comment]
Same issue:

```
Atom    : 1.21.2
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
xo: 0.18.2
linter-xo: 0.23.1
```

**Comment by sindresorhus** [comment]
I think this was fixed at some point?

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
