### ISSUE TITLE
Unresponsive UI with linter-xo enabled

### ISSUE THREAD

**Issue by simonepri** [xojs/atom-linter-xo#82]
If large binaries are present in the package, atom becomes unresponsive with `linter-xo` enabled.
Adding the incriminated folders to the `ignores` section didn't solve the problem.

version: `linter-xo 0.23.1` & `xo 0.18.2`

.gitignore
![image](https://user-images.githubusercontent.com/3505087/28228538-3eb5f6f2-68df-11e7-9f46-4c92859d8ac4.png)

XO configurations in package.json:
![image](https://user-images.githubusercontent.com/3505087/28228666-b5a3d202-68df-11e7-895b-e6d3514543e2.png)

The `bin` folder is `4GB`

**Comment by simonepri** [comment]
Changing:
```
"ignores": [
  "bin"
]
```
to:
```
"ignores": [
  "bin/**"
]
```
solved the problem.

It makes sense to you to add a little note about the needs of globs for `ignores` [here](https://github.com/sindresorhus/xo#ignores)?

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
