### ISSUE TITLE
xo causes atom to hang if it's linting a file that moves

### ISSUE THREAD

**Issue by OmgImAlexis** [xojs/atom-linter-xo#83]
I've noticed if I move a file while xo is still linting it that xo never finishes and Atom's RAM keeps climbing until it hits around 1.5GB and then hangs.

**Comment by sindresorhus** [comment]
That sounds more like a bug with Atom or Atom Linter.

**Comment by Arcanemagus** [comment]
Can you run `Linter: Debug` from the Command Palette on a file you see this on?
