### ISSUE TITLE
Allow to disable some rules when fixing on save

### ISSUE THREAD

**Issue by pvdlg** [xojs/atom-linter-xo#89]
The Fix on Save feature is really useful, but with some rules it can sometime get in the way.
For example with the [capitalized-comments](https://eslint.org/docs/rules/capitalized-comments).

When developing is sometimes to comment out a few lines of code to test something and revert the commenting to re-eanable the code.

With the `capitalized-comments` rule, if Fix on Save is enable, commenting a few line of code will capitalize the first letter. When un-commenting the capital letter will stay and has to be manually fixed.

For example, this following code might create a problem and I comment it to test:
```js
// if (condition) {
//   createPossibleProblem();
// }
```
On save `if` becomes `If`:
```js
// If (condition) {
//   createPossibleProblem();
// }
```
When I un-comment the code `If` stay capitalized.

See the same feature on [linter-eslint](https://github.com/AtomLinter/linter-eslint) : AtomLinter/linter-eslint#795

**Comment by pvdlg** [comment]
Related avajs/eslint-plugin-ava#173

Unfortunately since the `4.3.0` release of `eslint-plugin-ava` the fix on save feature has to be disabled if you use `ava`...

**Comment by sindresorhus** [comment]
Yes, this would be a useful feature. We could include some by default, like `capitalized-comments` and `ava/no-only-test`. Pull request welcome.
