### ISSUE TITLE
Linting in HTML documents does not work

### ISSUE THREAD

**Issue by sonicdoe** [xojs/atom-linter-xo#94]
![Screenshot](https://user-images.githubusercontent.com/652793/43325314-a39fc1be-91b6-11e8-91c7-5d6ac4898044.png)

XO seems to try to lint the whole HTML document instead of just the JavaScript code within the `<script>` tags.

**Comment by sindresorhus** [comment]
Probably because of https://github.com/xojs/atom-linter-xo/blob/1797d384b88f57b5147a1b58c082cc0d98be14a5/index.js#L12 I had assumed it would just get the text inside the script block then.

**Comment by sonicdoe** [comment]
Exactly 👍 For example, [linter-js-standard](https://github.com/ricardofbarros/linter-js-standard) (which I’m a maintainer of) [finds the code using regular expressions](https://github.com/ricardofbarros/linter-js-standard/blob/v5.1.0/lib/utils/html-splitter.js). Although, eventually I’d like to move to [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html) which is also used by [linter-eslint](https://github.com/AtomLinter/linter-eslint).

**Comment by sindresorhus** [comment]
I've removed the HTML scope. We should indeed use `eslint-plugin-html` instead.

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
