### ISSUE TITLE
Prettier 2 incompatible with Atom's node version.

### ISSUE THREAD

**Issue by mikebarnhardt** [xojs/atom-linter-xo#99]
Atom is stuck on `node@10.11` while `prettier@2.0.0` uses a method available in `node@10.12`.

Since upgrading to `xo@0.29`, I just get `createRequire is not a function` errors.

Manually downgrading for now…

https://github.com/prettier/prettier-atom/issues/725#issuecomment-613320843

**Comment by BarryThePenguin** [comment]
Now that the latest version of atom (1.57) is using node@12, I think there's nothing else to be done with this issue
